Social_Media/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
]

Social_Media/Social_Media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Social import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Social.urls')),
    path('', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Media/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pic')
    full_name = models.CharField(max_length=254,blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    instagram = models.URLField(blank=True)

    def __str__(self):
        return str(self.user)
    
class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

Social_Media/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username= forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1= forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2= forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Re-type Password'}))
    
    
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', }))
    class Meta:
        model = UserProfile
        exclude = ('user', )

Social_Media/App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from App_Login.models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from App_Social.forms import PostForm
from django.contrib.auth.models import User

# SEND MAIL
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.

# SIGNUP 
def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True 
            user_profile = UserProfile(user=user) #models.
            user_profile.save()

            # mail
            # login(request, user)
            # subject = 'Greetings!!!'
            # message = f'Hi, {user.username}, Thank you for joining us.'
            # email_from = settings.EMAIL_HOST_USER
            # recipient_list = [user.email,]
            # send_mail(subject, message, email_from, recipient_list)

            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title':'Sign Up, Instagram', 'form': form})  



# LOGIN
def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Social:home'))
    return render(request, "App_Login/login.html", context={'title': 'Login', 'form': form})        
                 
@login_required
def edit_profile(request):
    current_user =  UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, "App_Login/profile.html", context={'title': 'Edit Profile | Social', 'form': form})        


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("App_Login:login"))
 
#  postform
@login_required
def profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('App_Social:home'))
    return render(request, 'App_Login/user.html', context={'title':'My Profile | Social', 'form': form})

# other Profile
@login_required
def user(request, username):
    user_other=User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following = user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/user_other.html', context={'user_other':user_other, 'already_followed': already_followed})

# Follower
@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower = follower_user, following=following_user )
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username': username}))

# unfollow
@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower = follower_user, following=following_user )
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username':username}))

Social_Media/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock title_block %}
{% block css_block %}
<style>
    .log_in{
        width: 550px;
        margin: auto;
        border: 3px solid rgba(21, 94, 118, 0.806);
        padding: 25px;
    }
    .log_in form button{
        width: 100%;
        background-color: rgba(21, 94, 118, 0.806);
        color: azure;
    }
    .log_in h3{
        text-align: center;
        color: rgba(21, 94, 118, 0.806);
        padding-bottom: 20px;
        text-decoration: underline;
    }
    .sign_up{
        width: 550px;
        /* padding: 40px; */
        border: 2px solid #ccc;
        text-align: center;
        margin: auto;
    }
    
    </style> 
{% endblock css_block %}   

{% block body_block %}

<div class="log_in">
    <form action="" method="POST">
        {{form | crispy}}
        {% csrf_token %}
        <button type="submit">Login</button>
    </form>
</div>
<br>
<div class="sign_up">
    <p>Don't Have An Account? <a href="{% url 'App_Login:signup' %}"> Sign Up </a></p>
</div>

{% endblock body_block %}
    
    

Social_Media/templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock title_block %}
{% block css_block %}
<style>
    .profile{
        width: 550px;
        margin: auto;
        border: 3px solid rgba(21, 94, 118, 0.806);
        padding: 40px;
    }
    .profile form button{
        width: 100%;
        background-color: rgba(21, 94, 118, 0.806);
        color: azure;
    }
    .profile h3{
        text-align: center;
        color: rgba(21, 94, 118, 0.806);
        padding-bottom: 20px;
        text-decoration: underline;
    }
   </style> 
{% endblock css_block %}
    
{% block body_block %}
<div class="profile"> 
    <h3>My Profile</h3> 
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>














{% endblock  %}
    

Social_Media/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock title_block %}

<!-- css -->
{% block css_block %}
   <style>
    .sign_up{
        width: 550px;
        margin: auto;
        border: 3px solid rgba(21, 94, 118, 0.806);
        padding: 40px;
    }
    .sign_up form button{
        width: 100%;
        background-color: rgba(21, 94, 118, 0.806);
        color: azure;
    }
    .sign_up h3{
        text-align: center;
        color: rgba(21, 94, 118, 0.806);
        padding-bottom: 20px;
        text-decoration: underline;
    }
    .log_in{
        width: 550px;
        /* padding: 40px; */
        border: 2px solid #ccc;
        text-align: center;
        margin: auto;
    }

   </style> 
{% endblock css_block %}

<!-- form -->
{% block body_block %}
<div class="sign_up">
    <h3>Sign Up</h3>
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-sm">Sign Up</button>
        
        
    </form>
</div>
<br>
<div class="log_in">
    <p>Have an Account? <a href="{% url 'App_Login:login' %}"> Log In </a></p>
</div>
{% endblock body_block %}
    

Social_Media/templates/App_Login/user.html
{% extends 'navbar.html' %}
{% block title_block %}  {{user.user_profile.full_name}} (@{{user.username}})  {% endblock title_block %}



{% block css_block %}
    <style>
        .crop{
            width: 200px;
            height: 200px;
            overflow: hidden;          
        }
        .crop img{
            width: 400px;
            height: 300px;
            margin: -50px 50px 0px -100px;
        }
        
    </style>
{% endblock css_block %}



{% block body_block %}

<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="250px" alt="Profile Image" class="rounded-circle" >
        {% else %}
        <img src="/media/default.png" width="250px" height="250px" alt="Default Image" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>@{{user.username}} &nbsp; <a href="{% url 'App_Login:edit' %}" class="btn btn-light btn-sm">Edit Profile</a></h3><br>
        <h4> {{user.author_post.count}} Posts &nbsp; &nbsp; {{user.following.count}} Followers  &nbsp; &nbsp; {{user.follower.count}} Following</h4>
        <br>
        <h4>{{user.user_profile.full_name}}</h4>
        <h6>{{user.user_profile.description|linebreaks}}</h6>
    </div>
</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Post
</button>
 <!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Post A Photo</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
         <form method="POST" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-primary">Post</button>
         </form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
</div>
<br><br>
<div class="row">
    {% for post in user.author_post.all %}
    <div class="crop">
        <img src="/media/{{post.image}}" title="{{post.caption}}">
        <p>{{post.caption}}</p>
    </div>
    {% endfor %}
</div>


{% endblock body_block %}
 

Social_Media/templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{% block title_block %}  {{user_other.user_profile.full_name}} (@{{user_other.username}})  {% endblock title_block %}

{% block css_block %}
    <style>
        .crop{
            width: 200px;
            height: 200px;
            overflow: hidden;          
        }
        .crop img{
            width: 400px;
            height: 300px;
            margin: -75px 0 0 -100px;
        }
        
    </style>
{% endblock css_block %}

{% block body_block %}
 
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.profile_pic %}
        <img src="/media/{{user_other.user_profile.profile_pic}}" width="250px" height="250px" alt="Profile Image" class="rounded-circle" >
        {% else %}
        <img src="/media/default.png" width="250px" height="250px" alt="Default Image" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>@{{user_other.username}} &nbsp;            
            {% if not already_followed %}
            <a href="{% url 'App_Login:follow' username=user_other.username %}" class="btn btn-sm btn-primary">Follow</a>
            {% else %}
            <a href="{% url 'App_Login:unfollow' username=user_other.username %}" class="btn btn-sm btn-warning">Unfollow</a>
            {% endif %}
                
           </h3><br>   
        <h4> {{user_other.author_post.count}} Posts &nbsp; &nbsp; {{user_other.following.count}} Followers  &nbsp; &nbsp; {{user_other.follower.count}} Following</h4>
        <br>
        <h4>{{user_other.user_profile.full_name}}</h4>
        <h6>{{user_other.user_profile.description|linebreaks}}</h6>
    </div>
</div>
<hr>
<br><br>
<div class="row">
    {% for post in user_other.author_post.all %}
    <div class="crop">
        <img src="/media/{{post.image}}" title="{{post.caption}}">
        <p>{{post.caption}}</p>
    </div>
    {% endfor %}
</div>

{% endblock body_block %}