Social_Media/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
]

Social_Media/App_Social/urls.py
from django.urls import path
from App_Social import views

app_name = 'App_Social'

urlpatterns = [
    path("", views.home, name="home"),
]

Social_Media/Social_Media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Social import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Social.urls')),
    path('', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Media/App_Social/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-upload_date', ]


class Liked(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    liked_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)


     

Social_Media/App_Social/forms.py
from django import forms
from App_Social.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption',]

Social_Media/App_Social/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from App_Login.models import UserProfile,Follow
from django.contrib.auth.models import User

# Create your views here.

# Search
@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_Social/home.html', context={'title':'Home | Social', 'search': search, 'result':result, 'following_list': following_list})

Social_Media/templates/App_Social/home.html
{% extends 'navbar.html' %}
{% block title_block %} {{title}} {% endblock title_block %}
{% block body_block %}

{% if search %}
{% for user in result %}
<div class="row">
    <div class="col-sm-2">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" width="75px" height="75px" alt="Profile Image"
            class="rounded-circle">
        {% else %}
        <img src="/media/default.png" width="75px" height="75px" alt="Default Image" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-10">
        <a href="{% url 'App_Login:user' username=user.username %}"><b>@{{user.username}}</b></a>
        <br>
        {{user.user_profile.full_name}}
    </div>
</div>
<hr>
<br>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-sm-8">
        {% for author in following_list %}
        {% for post in author_post.following.post.all %}
        <div style="border: 1px solid hwb(0 53% 47%);">
            <div style="padding: 10px;">
                {{post.author}}
                {% if post.author_post.user_profile.profile_pic %}
                <img src="/media/{{user.user_profile.profile_pic}}" width="75px" height="75px" alt="Profile Image"
                    class="rounded-circle">
                {% else %}
                <img src="/media/default.png" width="75px" height="75px" alt="Default Image" class="rounded-circle">
                {% endif %}
                <a href="{% url 'App_Login:user' username=post.author_post %}">{{post.author}}</a>
            </div>
            <br>
            <img src="/media/{post.image}" width="100%" alt="">
        </div>
        <br><br>
        {% endfor %}
        {% endfor %}
    </div>
    <div class="col-sm-4">
        <div class="row">
            <div class="col-sm-4">
                {% if user.user_profile.profile_pic %}
                <img src="/media/{{user.user_profile.profile_pic}}" width="75px" height="75px" alt="Profile Image"
                    class="rounded-circle">
                {% else %}
                <img src="/media/default.png" width="75px" height="75px" alt="Default Image" class="rounded-circle">
                {% endif %}
            </div>
            <div class="col-sm-8">
                @{{user.username}}
                <br>
                {{user.user_profile.full_name}}
            </div>
        </div>

    </div>
</div>

{% endif %}

{% endblock body_block %}